### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by kentico-ericd** [kontent-ai/delivery-sdk-js#288]
### Motivation

[deno](https://deno.land/) v1 just released. It looks like it will gain a lot of traction and possible overtake Node at some point. It would be a good idea to provide support from the start to attract more projects and be ahead of the curve.

### Proposed solution

Add a `mod.ts` file (similar to deno's [fs](https://deno.land/std/fs/mod.ts) module) that allows users to `import` JS SDK modules. It should be fairly easy to implement as the changes should mostly related to the `imports` on ts modules.

Although, perhaps the reliance on rxjs will be a stopper, since that isn't deno-ready.

**Comment by Enngage** [comment]
@kentico-ericd could you possibly try testing the latest version of SDK with deno? We are no longer using `rxjs` and use only couple of deps.
