### ISSUE TITLE
urlResolver locale value in return value

### ISSUE THREAD

**Issue by stephenandekian** [kontent-ai/delivery-sdk-js#346]
### Motivation

It would be nice it he locale of the URL was returned back along with the ID, codename, urltext, etc. While I could assume the locale is relational to the content item for which it is being resolved there is no guarantee that the linked page isn't in another locale. Including the locale would allow for better URL formatting in the resolver. 

### Proposed solution

Return the locale value

**Comment by Enngage** [comment]
Hi,

I'm not quite sure what  `locale` value you mean. Can you possibly better explain where the SDK should get such a value? Some example of Delivery response and the result of `urlResolver` would help a lot.

**Comment by Enngage** [comment]
Closing this as it is not clear what should be implemented in SDK. Feel free to reopen.
