### ISSUE TITLE
Client Configuration Parameter to Bypass Archived Items

### ISSUE THREAD

**Issue by VladSelegean** [kontent-ai/delivery-sdk-js#349]
### Motivation
Using the **usePreviewMode** configuration also fetches archived items, which doesn't really make sense for the preview mode.

### Proposed solution
Adding a new configuration property which will skip archived items.

**Comment by Enngage** [comment]
Hi @VladSelegean,

I understand your point, though this is a feature of the Preview API itself, see a snapshot from our docs (https://kontent.ai/learn/reference/delivery-api/):

![preview](https://user-images.githubusercontent.com/7137351/174258031-07d22d73-d307-4ef7-a3b6-2014f9a3f8d4.png)

A possible workaround might be using the `system.workflow_step[neq]=archived` query parameter, though I'll have to test this first first too see if it works as intended.
