### ISSUE TITLE
Apply a global filter to deliveryClient

### ISSUE THREAD

**Issue by kevinmcgillicuddy** [kontent-ai/delivery-sdk-js#362]
### Motivation

I am looking to globally filter on `system.workflow_step` where the step is archive

Somewhat motivated by this [previous issue](https://github.com/kontent-ai/delivery-sdk-js/issues/349). We are using the delivery client in 2 pretty large Angular applications and what we do is initialize the delivery client once in a middleware library and then expose functions that get the various kontent items

example:
 
```typescript
this.client = new DeliveryClient({
      projectId: config.projectId ?? '',
      previewApiKey: config.previewApiKey,
      secureApiKey: config.secureApiKey,
       ...
```
and then in a class that extends the above class

```typescript
getContactInfo(): Observable<WFE.IContactInfo> {
return from(
      this.client
        .items<WWW.KontentContactInfoItem>()
        .type('contact_info')
        .toPromise()
    ).pipe(
      map((contactInfo) =>
        WWW.convertKontentContactInfoItem(contactInfo.data.items[0])
      )
    );
  }
``` 

so I can get it to work within every method (like getContactInfo above) adding in 
`.notEqualsFilter('system.workflow_step', 'archived');`

### Proposed solution

adding this to all the methods is less then ideal, what I would love is to be able to apply it on the delivery client initialization 

### Additional context

"@kontent-ai/delivery-sdk"
SDK version:
"12.4.3"

**Comment by Nickm615** [comment]
can you assign this to me?

**Comment by Nickm615** [comment]
Hi @kevinmcgillicuddy, are there any other filters you feel would be useful on a global client level? Right now I'm considering adding the option to exclude archived items as well as the option to set a default collection. Would this solve the issue for you is there more functionality you're hoping for?

**Comment by kevinmcgillicuddy** [comment]
> Hi @kevinmcgillicuddy, are there any other filters you feel would be useful on a global client level? Right now I'm considering adding the option to exclude archived items as well as the option to set a default collection. Would this solve the issue for you is there more functionality you're hoping for?

hey @Nickm615  the only use case I can think of right now was to exclude archived items. Thanks for taking this on! Anything I can do to help let me know
