### ISSUE TITLE
Default Language parameter is not overwritten when a language Parameter is applied at the query level

### ISSUE THREAD

**Issue by Nickm615** [kontent-ai/delivery-sdk-js#369]
### Brief bug description

The `defaultLanguage` parameter applied in the client should be overwritten when another language parameter is applied to an individual query, instead they are both applied

### Repro steps
Instantiate  a delivery client in a local JS environment
Add `defaultLanguage: 'yourLanguageCodename'` to the client
Create a query with `languageParameter` of another language applied
Send request and check URL value of the response object to see that both language parameters have been added.

My example:

```
const deliveryClient = new DeliveryClient({
    environmentId: 'a7ce696f-1479-0096-8d1d-f7a02aefa1d5',
    defaultLanguage: 'default'
})

const response = await(deliveryClient.items().languageParameter('es_ES').toAllPromise())
    

console.log(response.data.responses)
```

### Expected behavior

The Language Parameter on the query level should overwrite the default language, and the URL should only contain the single language parameter

### Test environment

Node.js v 18.16.0

### Additional context

I believe the issue is stemming from this:
https://github.com/kontent-ai/delivery-sdk-js/blob/master/lib/query/common/base-query.class.ts#L119-L128C6

![image](https://github.com/kontent-ai/delivery-sdk-js/assets/86981780/df852b31-e254-421e-9a0e-d90b97b743eb)

Specifically line 122, the `.find()` predicate will never return true, since the result of `this.getParameters()` isn't exactly equal to 'language'

**Comment by Nickm615** [comment]
@Enngage Could you assign this issue to me?

**Comment by Enngage** [comment]
@Nickm615 you got it and nice catch!

**Comment by Enngage** [comment]
Merged to main.
