### ISSUE TITLE
Axios needs to be updated to 1.6

### ISSUE THREAD

**Issue by pascavi** [kontent-ai/delivery-sdk-js#382]
### Brief bug description
One of the package dependencies has a vulnerability

What went wrong?
Axios needs to be upgraded from 1.4 to 1.6

### Repro steps
Install the latest version of the sdk using NPM. Use "npm audit" to see the report

### Expected behavior
No vulnerabilites are shown on npm audit

### Test environment

N/A

### Additional context

N/A

### Screenshots

N/A

**Comment by Enngage** [comment]
Fixed and will be released later Today.
