### ISSUE TITLE
vulnerability in follow-redirects package as dependency of axios package

### ISSUE THREAD

**Issue by sajcics** [kontent-ai/delivery-sdk-js#387]
### Brief bug description
 
What went wrong?
axios 1.6.2. reports that has vulnerable package follow-redirects 1.15.0. 

### Repro steps

1. run npm audit to check vulnerabilities
2. upgrade axios to newest version 1.6.7

### Expected behavior

What is the correct behavior?
To not have vulnerability packages. 

### Test environment

 - Node: v18

**Comment by IvanKiral** [comment]
hey @sajcics.
It seems that this will be fixed in newers versions https://github.com/axios/axios/issues/6165
I will update it :)

**Comment by Enngage** [comment]
Fixed and released in `14.7.0`
