### ISSUE TITLE
Support for new 'excludeElements' query string parameter

### ISSUE THREAD

**Issue by zdenekjurka** [kontent-ai/delivery-sdk-js#389]
### Motivation

Add support for new excludeElements query string parameter, that allows user to specify codenames of elements that should be excluded from API response.

### Proposed solution

SDK allows users to set 'excludeElements' query string parameter that takes comma separated list of element codenames that should be removed from API response.

### Additional context

Syntax is same as existing 'elements' filter.

**Comment by Enngage** [comment]
Released in `14.8.0`
